hostName: &hostname "todo-frontend.zone.internal"

ingress:
  enabled: true
  className: traefik
  host: *hostname
  serviceName: todo-frontend
  tls:
  - secretName: todo-frontend-tls
    hosts:
    - *hostname
  annotations:
    kubernetes.io/ingress.className: traefik
    cert-manager.io/cluster-issuer: local-ca
    external-dns.alpha.kubernetes.io/hostname: *hostname
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    #traefik.ingress.kubernetes.io/router.middlewares: "default-https-redirect@kubernetescrd"
    #traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.priority: "10"

image:
  repository: foxmuldercp/go-todo-frontend
  pullPolicy: IfNotPresent
  tag: latest

service:
  port: 80

backend:
  service:
    host: todo-backend.todo.svc.cluster.local
    port: 8080

resources:
  requests:
    cpu: "100m"
    memory: "0.1Gi"
  limits:
    cpu: "200m"
    memory: "0.2Gi"
