apiVersion: v2
name: todoapp
description: Umbrella chart for Todo App (backend + frontend)
type: application
version: 0.0.2
appVersion: "0.0.2"

dependencies:
- name: todo-backend
  version: 0.0.1
  repository: "file://charts/backend"
- name: todo-frontend
  version: 0.0.1
  repository: "file://charts/frontend"
