backend:
  enabled: true
  service:
    port: 8080
  image:
    repository: foxmuldercp/go-todo-backend
    tag: "latest"
  persistence:
    enabled: true
  env:
    STORAGE: /data/todo.db
    LISTEN_PORT: "8080"

frontend:
  enabled: true
  image:
    repository: foxmuldercp/go-todo-frontend
    tag: latest
  service:
    port: 80
  env:
    BACKEND_URL: "http://todo:8080"
