apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: {{ include "frontend.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    loki.io/logs: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "frontend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "frontend.fullname" . }}
        app.kubernetes.io/app: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/component: {{ include "frontend.fullname" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        alloy.io/scrape: "true"
        loki.io/logs: "true"
    spec:
      containers:
        - name: {{ include "frontend.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: nginx-vhost
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-main
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: nginx-main
          configMap:
            name: {{ include "frontend.fullname" . }}-nginx-main
        - name: nginx-vhost
          configMap:
            name: {{ include "frontend.fullname" . }}-nginx-vhost
