apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-nginx-main
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: {{ include "frontend.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /dev/stderr ;
    pid        /run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        log_format json_combined escape=json
          '{'
            '"time_local": "$time_local",'
            '"remote_addr": "$remote_addr",'
            '"request_method": "$request_method",'
            '"request_uri": "$request_uri",'
            '"server_protocol": "$server_protocol",'
            '"status": $status,'
            '"body_bytes_sent": $body_bytes_sent,'
            '"http_referer": "$http_referer",'
            '"http_user_agent": "$http_user_agent",'
            '"request_time": $request_time,'
            '"upstream_response_time": "$upstream_response_time",'
            '"host": "$host",'
            '"x_forwarded_for": "$http_x_forwarded_for"'
          '}';
        #access_log  /var/log/nginx/access.log  main;
        access_log /dev/stdout json_combined;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }