apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "backend.fullname" . }}-init-job"
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: {{ include "backend.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-weight": "5"
spec:
  template:
    spec:
      volumes:
        - name: init-script-volume
          configMap:
            name: "{{ include "backend.fullname" . }}-init-script"
            defaultMode: 0755
      containers:
        - name: init-job-container
          image: curlimages/curl:8.1.2
          command: ["/scripts/init.sh"]
          volumeMounts:
            - name: init-script-volume
              mountPath: /scripts
      restartPolicy: OnFailure
  backoffLimit: 3